BIN default_collision_map  "map/default.map"    2 2 0
BIN default_foreground_map "map/foreground.map" 2 2 0
BIN alternate_collision_map  "map/alternate.map"    2 2 0
BIN alternate_foreground_map "map/alternate-fg.map" 2 2 0
BIN default_background_map "map/background.map" 2 2 0
BIN results_background_map "map/results-bg.map" 2 2 0
BIN results_foreground_map "map/results-fg.map" 2 2 0
BIN title_foreground_map "map/title-fg.map" 2 2 0
BIN menu_foreground_map "map/menu-fg.map" 2 2 0